#!/usr/bin/env bash

case $BUTTON in
    1) setsid  fcitx-configtool ;;
	2) setsid st -e emacsclient -nc "~/.config/Scripts/input_method" ;;
esac


case $(fcitx-remote) in
    2) echo "🀄";;
    *) echo "🇪"
esac
