#!/usr/bin/env bash

case $1 in
    "emacs")
        notify-send "Restart" "Killing and restart Emacs in daemon"
        killall emacs
        ~/.emacs.d/bin/doom sync -e
        emacs --daemon
        ;;

esac
