#!/usr/bin/env bash

main () {
    action=$(echo -e "start\nstop\n" | dmenu)

    if [[ $action = "start" ]]; then
        killall xray
        local sel_config=$(ls ~/.config/x2ray | grep ".json" | dmenu -p "select config?")
        local config_path="$HOME/.config/x2ray/$sel_config"
        local addr=$(cat $config_path | grep address)
        xray run -config=$config_path &
        notify-send "Proxy" "✅ Start xray ✅ $addr"
    elif [[ $action = "stop" ]]; then
        killall xray
        [ -z $(pstree | grep xray) ] && notify-send "Proxy" "❌ Stop xray ❌"
    fi
}

main
